title: 3D Print on Fabric
hero_image: images/banner.png
description: Take clothing design to a new level with 3D art 
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
  - title: Introduction
  - title: Design
  - title: Slicing
  - title: Preparing the printer
