---
title: 3D print on fabric
hero_image: images/banner.jpg
description: Take clothing design to a new level with 3D art
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
- title: Introduction
- title: Design
- title: Slicing
- title: Preparing the printer
- title: Print
